name: example flow
on:
  push:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get code # Step name
        uses: actions/checkout@v3 # Action
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files # artifact name
          path: |
            dist
            package.json
  next-job:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: other things
        run: echo 'other'
        timeout-minutes: 25
