name: "Install dependencies"
description: "This install stuff..."
runs:
  using: "composite"
  steps:
    - name: Get code # Step name
      uses: actions/checkout@v3 # Action
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-$${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
