name: example flow
on:
  push:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo 'Hello'
      - name: bye
        run: echo 'bye'
  next-job:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: other things
        run: echo 'other'
        timeout-minutes: 25
