name: example flow
on:
  workflow_dispatch:
  push:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get code # Step name
        uses: actions/checkout@v3 # Action
      - name: Install dependencies
        run: npm ci
      - name: other things
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files # artifact name
          path: | # list of folders
            dist
            package.json
