name: example flow
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code # Step name
        uses: actions/checkout@v3 # Action
      - name: Install dependencies
        uses: "./.github/actions/install"
      - name: test
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code # Step name
        uses: actions/checkout@v3 # Action
      - name: Install dependencies
        uses: "./.github/actions/install"
      - name: build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files # artifact name
          path: | # list of folders
            dist
            package.json
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Get artifacts
        id: myId
        uses: actions/download-artifact@v3
        with:
          name: dist-files # artifact name
      - name: deploy
        run: echo 'Upload file... ${{ steps.myId.outputs.download-path }}'
